# Generated by Django 4.2.7 on 2023-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_organization_director_alter_sanction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='BIN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_owner',
            field=models.FloatField(null=True),
        ),
    ]
