# Generated by Django 4.2.7 on 2023-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_organization_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='decision_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='department_name',
            field=models.CharField(default='0', max_length=2550),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='essence_of_violation',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='imposed_penalty',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='name',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='period_of_execution',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type',
            field=models.CharField(choices=[('Банк второго уровня', 'Банк второго уровня'), ('Брокеры-дилеры', 'Брокеры-дилеры'), ('Кастодиан', 'Кастодиан')], default='Банк второго уровня', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type_of_penalty',
            field=models.CharField(choices=[('Меры по улучшению финансового состояния и (или) минимизации рисков (письменное предписание)', 'Меры по улучшению финансового состояния и (или) минимизации рисков (письменное предписание)'), ('Наложение административного штрафа', 'Наложение административного штрафа'), ('письменное предписание', 'письменное предписание'), ('письменное предупреждение', 'письменное предупреждение'), ('Предупреждение', 'Предупреждение'), ('письмо-обязательство', 'письмо-обязательство')], default='Наложение административного штрафа', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type_of_recovery',
            field=models.CharField(choices=[('Санкции и иные административные взыскания', 'Санкции и иные административные взыскания'), ('Меры надзорного реагирования', 'Меры надзорного реагирования'), ('Меры воздействия', 'Меры воздействия')], default='Меры воздействия', max_length=1000),
        ),
    ]
